#ifndef CODES_H_
#define CODES_H_

#define ESP32_ADDRESS 0x01
#define GET_INFO_CODE 0x23
#define SEND_INFO_CODE 0x16
#define GET_INTERNAL_TEMPERATURE_SUBCODE 0xc1
#define GET_REFERENCE_TEMPERATURE_SUBCODE 0xc2
#define GET_USER_COMMAND_SUBCODE 0xc3
#define SEND_C0NTROL_SIGNAL 0xd1
#define SEND_REFERENCE_SIGNAL 0xd2
#define SEND_SYSTEM_STATE 0xd3
#define SET_REFERENCE_TEMPERATURE_CONTROL_MODE 0xd4
#define SEND_FUNCTIONING_STATE 0xd5
#define SEND_AMBIENT_TEMPERATURE 0xd6
#define TURN_ON_OVEN 0xA1
#define TURN_OFF_OVEN 0xA2
#define START_WARMING 0xA3
#define CANCEL_PROCESS 0xA4
#define MENU 0xA5

#endif